# The latest versions are available at https://quiltmc.org/en/usage/latest-versions/
[versions]
minecraft = "26.1-snapshot-9"

fabric_loom = "1.15.3"
fabric_loader = "0.18.4"

fabric_api = "0.143.5+26.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }
