package deserthydra.cortex.datagen.common.loot;

import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.loot.LootTableSubProvider;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.storage.loot.BuiltInLootTables;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.EmptyLootItem;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.EnchantRandomlyFunction;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.functions.SetItemDamageFunction;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

import java.util.function.BiConsumer;

public record CortexChestLoot(HolderLookup.Provider registries) implements LootTableSubProvider {

	@Override
	public void generate(BiConsumer<ResourceKey<LootTable>, LootTable.Builder> output) {
		output.accept(BuiltInLootTables.BASTION_BRIDGE, createBastionBridge());
		output.accept(BuiltInLootTables.BASTION_HOGLIN_STABLE, createBastionHoglinStable());
		output.accept(BuiltInLootTables.BASTION_OTHER, createBastionOther());
		output.accept(BuiltInLootTables.BASTION_TREASURE, createBastionTreasure());
	}

	private LootTable.Builder createBastionBridge() {
		return LootTable.lootTable()
			.setRandomSequence(BuiltInLootTables.BASTION_BRIDGE.identifier())
			.withPool(LootPool.lootPool()
				.add(LootItem.lootTableItem(Items.LODESTONE))
			)
			.withPool(LootPool.lootPool()
				.setRolls(UniformGenerator.between(1.0F, 2.0F))
				.add(LootItem.lootTableItem(Items.CROSSBOW)
					.apply(SetItemDamageFunction.setDamage(UniformGenerator.between(0.1F, 0.5F)))
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
				)
				.add(LootItem.lootTableItem(Items.SPECTRAL_ARROW)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(10.0F, 28.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.GILDED_BLACKSTONE)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(8.0F, 12.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.CRYING_OBSIDIAN)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 8.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.GOLD_BLOCK))
				.add(LootItem.lootTableItem(Items.GOLD_INGOT)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F)))
				)
				.add(LootItem.lootTableItem(Items.IRON_INGOT)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F)))
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_SWORD)
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_AXE)
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_HELMET)
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_CHESTPLATE)
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_LEGGINGS)
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_BOOTS)
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
				)
			)
			.withPool(LootPool.lootPool()
				.setRolls(UniformGenerator.between(2.0F, 4.0F))
				.add(LootItem.lootTableItem(Items.STRING)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 6.0F)))
				)
				.add(LootItem.lootTableItem(Items.LEATHER)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 3.0F)))
				)
				.add(LootItem.lootTableItem(Items.ARROW)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(5.0F, 12.0F)))
				)
				.add(LootItem.lootTableItem(Items.GOLD_NUGGET)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 6.0F)))
				)
				.add(LootItem.lootTableItem(Items.IRON_NUGGET)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 6.0F)))
				)
			)
			.withPool(LootPool.lootPool()
				.add(EmptyLootItem.emptyItem()
					.setWeight(11)
				)
				.add(LootItem.lootTableItem(Items.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE))
			);
	}

	private LootTable.Builder createBastionHoglinStable() {
		return LootTable.lootTable()
			.setRandomSequence(BuiltInLootTables.BASTION_HOGLIN_STABLE.identifier())
			.withPool(LootPool.lootPool()
				.add(LootItem.lootTableItem(Items.DIAMOND_SHOVEL)
					.apply(SetItemDamageFunction.setDamage(UniformGenerator.between(0.15F, 0.8F)))
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
					.setWeight(15)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_PICKAXE)
					.apply(SetItemDamageFunction.setDamage(UniformGenerator.between(0.15F, 0.95F)))
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
					.setWeight(12)
				)
				.add(LootItem.lootTableItem(Items.SADDLE)
					.setWeight(12)
				)
				.add(LootItem.lootTableItem(Blocks.GOLD_BLOCK)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 4.0F)))
					.setWeight(16)
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_CARROT)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(8.0F, 17.0F)))
					.setWeight(10)
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
					.setWeight(10)
				)
			)
			.withPool(LootPool.lootPool()
				.setRolls(UniformGenerator.between(3.0F, 4.0F))
				.add(LootItem.lootTableItem(Items.GOLDEN_AXE)
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
				)
				.add(LootItem.lootTableItem(Items.GOLD_NUGGET)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 8.0F)))
				)
				.add(LootItem.lootTableItem(Items.LEATHER)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 3.0F)))
				)
				.add(LootItem.lootTableItem(Items.ARROW)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(5.0F, 17.0F)))
				)
				.add(LootItem.lootTableItem(Items.STRING)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 8.0F)))
				)
				.add(LootItem.lootTableItem(Items.PORKCHOP)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 5.0F)))
				)
				.add(LootItem.lootTableItem(Items.COOKED_PORKCHOP)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 5.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.CRYING_OBSIDIAN)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 5.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.GLOWSTONE)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 6.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.GILDED_BLACKSTONE)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 5.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.SOUL_SAND)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 7.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.CRIMSON_NYLIUM)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 7.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.CRIMSON_FUNGUS)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 7.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.CRIMSON_ROOTS)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 7.0F)))
				)
			)
			.withPool(LootPool.lootPool()
				.add(EmptyLootItem.emptyItem()
					.setWeight(11)
				)
				.add(LootItem.lootTableItem(Items.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE))
			);
	}

	private LootTable.Builder createBastionOther() {
		var enchantments = registries.lookupOrThrow(Registries.ENCHANTMENT);
		return LootTable.lootTable()
			.setRandomSequence(BuiltInLootTables.BASTION_OTHER.identifier())
			.withPool(LootPool.lootPool()
				.add(LootItem.lootTableItem(Items.DIAMOND_SHOVEL)
					.setWeight(6)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_PICKAXE)
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
					.setWeight(6)
				)
				.add(LootItem.lootTableItem(Items.CROSSBOW)
					.apply(SetItemDamageFunction.setDamage(UniformGenerator.between(0.1F, 0.9F)))
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
					.setWeight(6)
				)
				.add(LootItem.lootTableItem(Items.SPECTRAL_ARROW)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(10.0F, 22.0F)))
					.setWeight(10)
				)
				.add(LootItem.lootTableItem(Items.PIGLIN_BANNER_PATTERN)
					.setWeight(9)
				)
				.add(LootItem.lootTableItem(Items.MUSIC_DISC_PIGSTEP)
					.setWeight(5)
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_CARROT)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(6.0F, 17.0F)))
					.setWeight(12)
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_APPLE)
					.setWeight(9)
				)
				.add(LootItem.lootTableItem(Items.BOOK)
					.apply(EnchantRandomlyFunction.randomEnchantment().withEnchantment(enchantments.getOrThrow(Enchantments.SOUL_SPEED)))
					.setWeight(10)
				)
			)
			.withPool(LootPool.lootPool()
				.setRolls(ConstantValue.exactly(2.0F))
				.add(LootItem.lootTableItem(Items.IRON_SWORD)
					.apply(SetItemDamageFunction.setDamage(UniformGenerator.between(0.1F, 0.9F)))
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
					.setWeight(2)
				)
				.add(LootItem.lootTableItem(Blocks.IRON_BLOCK)
					.setWeight(2)
				)
				.add(LootItem.lootTableItem(Blocks.GOLD_BLOCK)
					.setWeight(2)
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_BOOTS)
					.apply(EnchantRandomlyFunction.randomEnchantment().withEnchantment(enchantments.getOrThrow(Enchantments.SOUL_SPEED)))
				)
				.add(LootItem.lootTableItem(Items.GOLDEN_AXE)
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
				)
				.add(LootItem.lootTableItem(Items.CROSSBOW))
				.add(LootItem.lootTableItem(Items.GOLDEN_SWORD))
				.add(LootItem.lootTableItem(Items.GOLDEN_HELMET))
				.add(LootItem.lootTableItem(Items.GOLDEN_CHESTPLATE))
				.add(LootItem.lootTableItem(Items.GOLDEN_LEGGINGS))
				.add(LootItem.lootTableItem(Items.GOLDEN_BOOTS))
				.add(LootItem.lootTableItem(Items.GOLD_INGOT)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 6.0F)))
					.setWeight(2)
				)
				.add(LootItem.lootTableItem(Items.IRON_INGOT)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 6.0F)))
					.setWeight(2)
				)
				.add(LootItem.lootTableItem(Blocks.CRYING_OBSIDIAN)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 5.0F)))
					.setWeight(2)
				)
			)
			.withPool(LootPool.lootPool()
				.setRolls(UniformGenerator.between(3.0F, 4.0F))
				.add(LootItem.lootTableItem(Blocks.GILDED_BLACKSTONE)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 5.0F)))
					.setWeight(2)
				)
				.add(LootItem.lootTableItem(Blocks.IRON_CHAIN)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 10.0F)))
				)
				.add(LootItem.lootTableItem(Items.MAGMA_CREAM)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 6.0F)))
					.setWeight(2)
				)
				.add(LootItem.lootTableItem(Blocks.BONE_BLOCK)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 6.0F)))
				)
				.add(LootItem.lootTableItem(Items.IRON_NUGGET)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 8.0F)))
				)
				.add(LootItem.lootTableItem(Items.GOLD_NUGGET)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 8.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.OBSIDIAN)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 6.0F)))
				)
				.add(LootItem.lootTableItem(Items.STRING)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 6.0F)))
				)
				.add(LootItem.lootTableItem(Items.ARROW)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(5.0F, 17.0F)))
					.setWeight(2)
				)
				.add(LootItem.lootTableItem(Items.COOKED_PORKCHOP))
			)
			.withPool(LootPool.lootPool()
				.add(EmptyLootItem.emptyItem()
					.setWeight(11)
				)
				.add(LootItem.lootTableItem(Items.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE))
			);
	}

	private LootTable.Builder createBastionTreasure() {
		return LootTable.lootTable()
			.setRandomSequence(BuiltInLootTables.BASTION_TREASURE.identifier())
			.withPool(LootPool.lootPool()
				.setRolls(ConstantValue.exactly(3.0F))
				.add(LootItem.lootTableItem(Items.DIAMOND_SWORD)
					.apply(SetItemDamageFunction.setDamage(UniformGenerator.between(0.8F, 1.0F)))
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
					.setWeight(6)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_SWORD)
					.setWeight(6)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_HELMET)
					.apply(SetItemDamageFunction.setDamage(UniformGenerator.between(0.8F, 1.0F)))
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
					.setWeight(6)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_CHESTPLATE)
					.apply(SetItemDamageFunction.setDamage(UniformGenerator.between(0.8F, 1.0F)))
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
					.setWeight(6)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_LEGGINGS)
					.apply(SetItemDamageFunction.setDamage(UniformGenerator.between(0.8F, 1.0F)))
					.apply(EnchantRandomlyFunction.randomApplicableEnchantment(registries))
					.setWeight(6)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_BOOTS)
					.setWeight(5)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_HELMET)
					.setWeight(5)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_CHESTPLATE)
					.setWeight(5)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_LEGGINGS)
					.setWeight(5)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND_BOOTS)
					.setWeight(5)
				)
				.add(LootItem.lootTableItem(Items.DIAMOND)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 6.0F)))
					.setWeight(5)
				)
				.add(LootItem.lootTableItem(Items.ENCHANTED_GOLDEN_APPLE)
					.setWeight(2)
				)
			)
			.withPool(LootPool.lootPool()
				.setRolls(UniformGenerator.between(3.0F, 4.0F))
				.add(LootItem.lootTableItem(Items.SPECTRAL_ARROW)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(12.0F, 25.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.GOLD_BLOCK)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 5.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.IRON_BLOCK)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 5.0F)))
				)
				.add(LootItem.lootTableItem(Items.GOLD_INGOT)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 9.0F)))
				)
				.add(LootItem.lootTableItem(Items.IRON_INGOT)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 9.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.CRYING_OBSIDIAN)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 5.0F)))
				)
				.add(LootItem.lootTableItem(Items.QUARTZ)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(8.0F, 23.0F)))
				)
				.add(LootItem.lootTableItem(Blocks.GILDED_BLACKSTONE)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(5.0F, 15.0F)))
				)
				.add(LootItem.lootTableItem(Items.MAGMA_CREAM)
					.apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 8.0F)))
				)
			)
			.withPool(LootPool.lootPool()
				.add(EmptyLootItem.emptyItem()
					.setWeight(11)
				)
				.add(LootItem.lootTableItem(Items.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE))
			);
	}
}
