name: Build Status
on: push

env:
  JAVA_VERSION: 25

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v6
        with:
          distribution: microsoft
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}
          path: build/libs
