name: Build Mod
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Channel'
        required: true
        default: 'STABLE'
        type: choice
        options:
          - STABLE
          - BETA
          - ALPHA
      changelog:
        description: 'Changelog'
        required: true
        type: string
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Eclipse Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Publish with Gradle
        run: gradle build publishMods
        env:
          CHANNEL: ${{ inputs.channel }}
          CHANGELOG: ${{ inputs.changelog }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
